### ISSUE TITLE
python3 logtailer.py output

### ISSUE THREAD

**Issue by chuck56ri** [dg9vh/WSYSFDash#6]
help!
root@ctridigital:/opt/WSYSFDash# python3 ./logtailer.py
2021-07-20 10:38:02,911 INFO Starting Websocketserver
Traceback (most recent call last):
  File "/opt/WSYSFDash/./logtailer.py", line 200, in <module>
    main()
  File "/opt/WSYSFDash/./logtailer.py", line 196, in main
    websocketserver()
  File "/opt/WSYSFDash/./logtailer.py", line 190, in websocketserver
    asyncio.get_event_loop().run_until_complete(start_server)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/asyncio/tasks.py", line 690, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5678): address already in use

**Comment by 9Y4C** [comment]
The service is already running if you're getting that error to the end, you
have to stop the service before trying to start it manually.

**Comment by dg9vh** [comment]
That's it :-)

**Comment by ki5gnl** [comment]
can you tell me how to open dashboard without the :8000   can i change it to port 80?

**Comment by chuck56ri** [comment]
> 

Yes, you can change the port by logging in to the server as root and do the following.
cd /etc/apache2
nano ports.conf
Note the text at the top of ports.conf where is talks about virtual host

**Comment by dg9vh** [comment]
You can also modify https://github.com/dg9vh/WSYSFDash/blob/main/systemd/http.server.service#L12 - in this command the port for the webserver is configured.
73 de Kim
